### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Heyter** [LilSumac/bash-srp-archive-1#2]
```
[ERROR] lua/includes/extensions/table.lua:150: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Count - lua/includes/extensions/table.lua:150
    3. oldFunc - gamemodes/srp_alpha/gamemode/hooks/cl_hooks.lua:535
```

```
[ERROR] gamemodes/srp_alpha/gamemode/modules/srp_pda/vgui/vgui_apps.lua:818: attempt to index a nil value
  1. oldFunc - gamemodes/srp_alpha/gamemode/modules/srp_pda/vgui/vgui_apps.lua:818
   2. Action - addons/dbugr-master/lua/dbugr/util/modules/sh_func.lua:80
    3. DoClick - gamemodes/srp_alpha/gamemode/modules/srp_pda/vgui/vgui_pda.lua:382
     4. unknown - lua/vgui/dlabel.lua:232
```

```
[ERROR] gamemodes/srp_alpha/gamemode/vgui/vgui_inventoryobj.lua:1007: attempt to get length of a userdata value
  1. DoDrop - gamemodes/srp_alpha/gamemode/vgui/vgui_inventoryobj.lua:1007
   2. unknown - gamemodes/srp_alpha/gamemode/vgui/vgui_inventoryobj.lua:48
```

```
[ERROR] gamemodes/srp_alpha/gamemode/modules/srp_pda/vgui/vgui_apps.lua:1141: attempt to index field 'MemoryData' (a nil value)
  1. oldFunc - gamemodes/srp_alpha/gamemode/modules/srp_pda/vgui/vgui_apps.lua:1141
   2. Action - addons/dbugr-master/lua/dbugr/util/modules/sh_func.lua:80
    3. DoClick - gamemodes/srp_alpha/gamemode/modules/srp_pda/vgui/vgui_pda.lua:382
     4. unknown - lua/vgui/dlabel.lua:232
```

**Comment by Heyter** [comment]
Using pon.encode/decode for JSON. [for optimization]
pon faster than JSON.

**Comment by LilSumac** [comment]
Hey, thanks for the feedback! I'll address these errors by number:

1) What kind of SWEPs are you using? Do you have the bash_wep_base installed from the content pack? This is a pretty common error that usually stems from the fact that the supplied SWEPs aren't installed. Unfortunately they are hard-coded into the gamemode itself, a feature I overlooked during development.

2) This is a bug from my end, I'll commit a change when I can that rectifies this. In the mean time, take a look at the maps/ directory and read through the files already there. Each one contains a table structure that provides some information about the map, such as the bounds and spawn points. Feel free to make your own map file in the mean time.

3) This one is a little perplexing, and I will look into it further. It may be a simple bug on my part.

4) Have you tried deleting the specific PDA item you're using and creating a new one? Also, make sure you correctly replaced the JSON parsing going on in the sv_pda.lua file.

I'll try and recreate these on my end.

**Comment by Heyter** [comment]
Add drop loot if player dead.
